### ISSUE TITLE
Fix alphabetic sorts

### ISSUE THREAD

**Issue by LOZORD** [UW-UPL/uw-upl.github.io#101]
It appears that Jekyll does not do a case-ignoring alphabetic sort. Is this worthwhile to change?

Basically, which is The Correct Order™?

```js
['XYZ', 'abc']
// or
['abc', 'XYZ']
```

**Comment by zthomae** [comment]
I'm aware of this and agree that it's not ideal. I think the best solution is to wait for GitHub to upgrade the version of Jekyll they use so we can get [the upstream commit](https://github.com/Shopify/liquid/commit/03b3446119c83e5c89e3b7207042d1c1f6756917) that fixes this.

**Comment by LOZORD** [comment]
Awesome 👍  I'll make my sorting case-ignorant.
