### ISSUE TITLE
Add cool console welcome message

### ISSUE THREAD

**Issue by LOZORD** [UW-UPL/uw-upl.github.io#102]
I know I'm reversing my stance (see #55), but it might be cool to have a welcome message in the console for hackers :neckbeard: I think Mozilla used to do something like this 😎

**Comment by zthomae** [comment]
Someone can do this if they want.

**Comment by LOZORD** [comment]
Something any of the new coords or website-uninitiated want?

@ekivolowitz @ChristianBorst @mhorowitzgelb @simplywondrous @bhans117 @ranman166 ?

This would be a fun way to hack on the website 😄

**Comment by MikeCook9994** [comment]
Honestly....we might want to consider a scavenger hunt or something in the future. This might be fun to do on a bigger scale.

**Comment by LOZORD** [comment]
Thanks my dude!
