### ISSUE TITLE
Consider Google Page Speed Guidelines

### ISSUE THREAD

**Issue by katamaritaco** [UW-UPL/uw-upl.github.io#107]
I still can't access upl.cs.wisc.edu at home, but uwing uw-upl.github.io in Google's tool gives some nice results that are worth addressing.

https://developers.google.com/speed/pagespeed/insights/?url=https%3A%2F%2Fuw-upl.github.io%2F&tab=desktop

**Comment by ekivolowitz** [comment]
Closing for now. If someone wants to do this, then reopen the issue.
