### ISSUE TITLE
Issue with Siren webcam

### ISSUE THREAD

**Issue by dlinning** [UW-UPL/uw-upl.github.io#110]
When the page is first loaded,
`Mixed Content: The page at 'https://uw-upl.github.io/#/' was loaded over HTTPS, but requested an insecure image 'http://siren.upl.cs.wisc.edu:1312/webcam-frame.jpg?0.3897509250254363'. This content should also be served over HTTPS.`
is displayed in the console.

Clicking the preview image to show the livestream results in similar messages being spammed in the console.

As far as I know, changing the source from `http://siren.upl...` to `https://siren.upl...` should fix this issue.

Edit: Looking at another issue, it seems that SSL Certs are an issue. I would suggest Cloudflare for that.

**Comment by jdetter** [comment]
@Squeakrats do you wana take this one?

**Comment by Squeakrats** [comment]
Sure, Ricky got certs already I think.

**Comment by Ricky54326** [comment]
Merging #76 here. Will try to look at this over the break.

**Comment by Squeakrats** [comment]
this was fixed with the webcam going back to webm
