### ISSUE TITLE
Adding "report" form for reporting lab status + user complaints + missing hours

### ISSUE THREAD

**Issue by Ricky54326** [UW-UPL/uw-upl.github.io#112]
Embed a google form or something into the site that users can file complaints on, anonymously. Some people have complained before but are scared of retaliation which is understandable.

**Comment by Ricky54326** [comment]
🐫

**Comment by Squeakrats** [comment]
I'll do this over break

**Comment by Squeakrats** [comment]
This was done awhile ago but never closed. closing
