### ISSUE TITLE
The download button on the web player starts a file download that seems to transfer forever.

### ISSUE THREAD

**Issue by MikeCook9994** [UW-UPL/uw-upl.github.io#114]
I believe it starts a download of the stream itself but never actually terminates. Didn't investigate the issue fully though.

**Comment by LOZORD** [comment]
Try turning off the controls?

**Comment by MikeCook9994** [comment]
This would be be good AFAIK. They currently have no function anyways on desktop. Would this impact mobile?

**Comment by LOZORD** [comment]
Try it out ¯\_(ツ)_/¯

**Comment by MikeCook9994** [comment]
Is that what they're teaching you at Google University?

**Comment by LOZORD** [comment]
Is that what they are teaching you at UW-Madison?
![justdoit](https://cloud.githubusercontent.com/assets/3687761/21536659/8765258a-cd53-11e6-969b-e316cb8dca4c.gif)
