### ISSUE TITLE
Add Andrew as a Coord

### ISSUE THREAD

**Issue by ekivolowitz** [UW-UPL/uw-upl.github.io#118]
Go to _data folder and follow the format of the other coords for adding yourself to the site in the coords.yaml file. You can do this directly in the browser edit mode if you wish. I'm not sure where the list of emojis are.

**Comment by ekivolowitz** [comment]
I am going to add Andrew as a Coord and assign this to him. It's assigned to me temporarily.

**Comment by Andretti77** [comment]
Added all the things.
