### ISSUE TITLE
Pull GitHub profile picture?

### ISSUE THREAD

**Issue by LOZORD** [UW-UPL/uw-upl.github.io#14]
If a coord doesn't provide a photo, would we want to pull their GitHub profile picture? This is just proverbial icing on the :cake: .

**Comment by katamaritaco** [comment]
Should pull Gravatar instead if anything if possible

**Comment by LOZORD** [comment]
We can pull the photo by using the following JSON (my profile for example):
https://api.github.com/users/lozord

**Comment by katamaritaco** [comment]
Sounds too complex for the system we want. People should upload their own photos :camera:

**Comment by katamaritaco** [comment]
KISS
