### ISSUE TITLE
Allow HTML or Markdown inside Event descriptions

### ISSUE THREAD

**Issue by LOZORD** [UW-UPL/uw-upl.github.io#16]
I could see this being very useful in the future.

Might just need to use `ng-bind` or something along the lines of [this answer](http://stackoverflow.com/questions/9381926/angularjs-insert-html-into-view).

**Comment by mjneil** [comment]
Its a little more complicated but easily doable. Although I'm not sure I 100% agree with the usefulness. I think its important we keep with consistency on design and a standard for event content

**Comment by LOZORD** [comment]
What if we want to link to an FB event or a repo?

**Comment by mjneil** [comment]
Makes sense. I was thinking more like you wanted people adding divs and layout markup which could just become messy so I'd want that type of markup avoided, but I see what you mean

**Comment by katamaritaco** [comment]
Can we allow only emoji support within these specific HTMLs?

**Comment by LOZORD** [comment]
Just added the ability to use HTML in descriptions. Do people want Markdown as well?

https://github.com/btford/angular-markdown-directive

**Comment by katamaritaco** [comment]
I personally find markdown a lot easier to write in, but I think you and I are the only ones L O Z O R D

**Comment by LOZORD** [comment]
I agree that Markdown is easier, but I think for the most part, we (I) only want this for link-embedding. HTML is also "easier" in that the average coord doesn't have to learn a new syntax. For now, I will close unless a majority want Markdown too.
