### ISSUE TITLE
Make a nice readme

### ISSUE THREAD

**Issue by katamaritaco** [UW-UPL/uw-upl.github.io#2]
Make a nice readme

**Comment by LOZORD** [comment]
@mjneil How do I serve the website locally?

**Comment by mjneil** [comment]
Each folder within the content/ directory also needs readmes

**Comment by mjneil** [comment]
Accidently closed this, didn't mean to.

@LOZORD to run locally, just make sure you have python installed. then go to the local directory the site is on your terminal and run

`python -m SimpleHTTPServer 8080`

**Comment by mjneil** [comment]
Reopening as the readme will need more info such as

How to use sass to compile the CSS for the site
More I can't think of atm

**Comment by melutzke** [comment]
A package file that allows you to do
npm install
npm build (for generating new CSS files)
and
npm start
Would be super coolio

**Comment by LOZORD** [comment]
Would this be a good use for [webpack](https://webpack.github.io/)?

**Comment by katamaritaco** [comment]
SASS Stuff in https://github.com/UW-UPL/uw-upl.github.io/tree/master/styles for now
