### ISSUE TITLE
Featuring projects on the homepage

### ISSUE THREAD

**Issue by mjneil** [UW-UPL/uw-upl.github.io#21]
How do we want to feature projects on the homepage. I am in the progress of making it so it just picks 3 random projects from the list of projects to put on the homepage. We could also make it something that we manually set in the json and update ourselves every now and then. Any other ideas?

**Comment by katamaritaco** [comment]
I think we can/should only show one, as long as has nice description. I think it'd be great to use that as a showcase for our community, and cycle through the projects (and talks, writeups too) throughout time.

Lmk if what I said was confusing

Sent from Outlook Mobile<https://aka.ms/blhgte>



On Tue, Jan 26, 2016 at 12:33 PM -0800, "Matthew Neil" <notifications@github.com<mailto:notifications@github.com>> wrote:


How do we want to feature projects on the homepage. I am in the progress of making it so it just picks 3 random projects from the list of projects to put on the homepage. We could also make it something that we manually set in the json and update ourselves every now and then. Any other ideas?

-

**Comment by LOZORD** [comment]
Why not set up some sort of [carousel](https://getbootstrap.com/examples/carousel/) type element?

**Comment by melutzke** [comment]
a featured project could be cool, and could be rotated over time manually.

**Comment by LOZORD** [comment]
@melutzke maybe add a `featured` flag to `projects.json`?

**Comment by melutzke** [comment]
that might be a good idea. Bonus points if it's a more self documenting featured_on_homepage or featuredOnHomepage flag

**Comment by mjneil** [comment]
@katamaritaco what you said is confusing

@LOZORD http://shouldiuseacarousel.com/ also writing carousels sucks so much, and what mitch said about easy manual 

and ya the featured flag in projects.json was what I was thinking would be an easy solution to manual updates

**Comment by katamaritaco** [comment]
Mitchell said exactly what I meant. So we're all good.

Sent from Outlook Mobile<https://aka.ms/blhgte>



On Tue, Jan 26, 2016 at 2:29 PM -0800, "Matthew Neil" <notifications@github.com<mailto:notifications@github.com>> wrote:


@katamaritaco<https://github.com/katamaritaco> what you said is confusing

@LOZORD<https://github.com/LOZORD> http://shouldiuseacarousel.com/ also writing carousels sucks so much, and what mitch said about easy manual

and ya the featured flag in projects.json was what I was thinking would be an easy solution to manual updates

-

**Comment by lwdinh** [comment]
I know we are the Undergraduate *Projects* Lab, but maybe there is something more useful we could put on the home page? Just thought to bring this up before we commit to putting it on. The homepage projects on the current site isn't even used.

What if we added a chat feed into the site?

**Comment by mjneil** [comment]
Just because we feature one or more projects on the homepage does not mean we cannot have anything else on the homepage. Showing off some projects on the homepage is important I think. It's not really used right now because no one updates the current site for multiple reasons, probably the biggest being how much of a mess it is.

So having more things on the homepage is definitely something we can and should do, and I encourage a discussion on things we can add.

For your ideas specifically, what do you mean by chat feed? Like an actual chat room? I think that is a bad idea.

We could add a facebook thing, but I'm not sure what facebook's apis are like for groups. We don't have an offical UPL page that makes posts, but a group instead. Will have to look into what is available for us there. 

Could also add a twitter feed if people wanted to, although we would need someone to start actively using the twitter. https://twitter.com/UWMadisonUPL 

I think having a link and instructions for donating to the upl is a great idea, but since we dont directly handle the donations, I don't see a reason to have an actual form on the page.

**Comment by melutzke** [comment]
if we could embed the UPL fb group on the page so people could see the latest postings, I think that would be pretty cool, and helpful to directing them to the group.

**Comment by katamaritaco** [comment]
Would definitely love to have a section for upcoming events. People are always asking about that. Would be great to have the next coming event/talk on there as well.

**Comment by LOZORD** [comment]
See related PR #54

**Comment by katamaritaco** [comment]
@mjneil
