### ISSUE TITLE
Auto-crop coord images to perfect circle

### ISSUE THREAD

**Issue by LOZORD** [UW-UPL/uw-upl.github.io#23]
Because :sunglasses: 

http://sixrevisions.com/css/circular-images-css/

**Comment by mjneil** [comment]
1. This still requires the assumption that the "subject" is in a certain position. So it still requires manual work from each person to make sure their photo wont auto crop to showing their crotch or something. At that point, might as well just upload a square image.

2. KISS

**Comment by LOZORD** [comment]
I'm fine with simplicity, just if people care about the oblong photos.

**Comment by katamaritaco** [comment]
KISS L O Z O R D
