### ISSUE TITLE
Event pictures don't actually do anything.

### ISSUE THREAD

**Issue by lwdinh** [UW-UPL/uw-upl.github.io#25]
Maybe take them out or incorporate them into the specific event page.

**Comment by mjneil** [comment]
I commented it out of the html for now as I didn't have any concrete design ideas for them. We can and will definitely incorporate into the specific event page. Doesn't hurt anything to have them in the json for now without using it in the html

**Comment by lwdinh** [comment]
Sweet. I'm going to just make it so that if there is a picture, it ends up on the event page. Speaking of the event page though, eventually it would be a good idea to add an extra json field for both "description" and "more info." There's little point in the event pages having their own pages as it is.

Additionally, for future reference before I forget, the horizontal lines are inconsistent in width between the event dividers and the main top divider.

**Comment by lwdinh** [comment]
Also, I haven't done it yet, but it would also be good for the picture size to be limited in width and height. Do you know a good way of cropping pictures (or at least limiting width/height?)

**Comment by lwdinh** [comment]
And the horizontal divider at the bottom should have a minimum distance from the footer so it doesn't look bad.

**Comment by LOZORD** [comment]
:camel: cruft or keep?

**Comment by LOZORD** [comment]
Can we close this now?

**Comment by spwilson2** [comment]
:camel:
