### ISSUE TITLE
Remove policy-related strings from About page

### ISSUE THREAD

**Issue by LOZORD** [UW-UPL/uw-upl.github.io#27]
We have the [Documentation](https://github.com/UW-UPL/Documentation) repo for a lot of this stuff.

Basically, what cruft can we remove from the About page?

**Comment by lwdinh** [comment]
I think it's mostly alright. Some things might be out of date, like sending mail.
One particular change might be to remove the "Disk Space" question, as it doesn't seem very important compared to the other stuff.

What changes did you have in mind?

**Comment by lwdinh** [comment]
Linking the library directly might be good.

**Comment by lwdinh** [comment]
Switching the order of some of the questions also might be good.

**Comment by lwdinh** [comment]
The recent change to minimize questions also got rid of all the links on the page.

**Comment by mjneil** [comment]
> The recent change to minimize questions also got rid of all the links on the page.

@zthomae

**Comment by zthomae** [comment]
Derp

**Comment by katamaritaco** [comment]
Think it all mostly needs overhaul. See #33
