### ISSUE TITLE
Add 'website' field for the json :alien:

### ISSUE THREAD

**Issue by katamaritaco** [UW-UPL/uw-upl.github.io#31]
It'd be nice to have a custom 'website' alongside a github account on the coords page. This could be a facebook page, personal website, twitter profile, whatever. Would just be nice if somebody would like to contact somebody.

:guitar:

**Comment by mjneil** [comment]
Go for it

**Comment by katamaritaco** [comment]
I WASNT ASKING PERMISSION

**Comment by mjneil** [comment]
Was giving support, not granting permission

**Comment by katamaritaco** [comment]
:heart: u mat
