### ISSUE TITLE
Emoji support on website

### ISSUE THREAD

**Issue by katamaritaco** [UW-UPL/uw-upl.github.io#32]
does work?

**Comment by LOZORD** [comment]
Does [this](http://afeld.github.io/emoji-css/) work for you?

**Comment by katamaritaco** [comment]
Up to @mneil

Sent from Outlook Mobile<https://aka.ms/blhgte>



On Fri, Jan 29, 2016 at 10:02 PM -0800, "Leo Rudberg" <notifications@github.com<mailto:notifications@github.com>> wrote:


Does this<http://afeld.github.io/emoji-css/> work for you?

-

**Comment by katamaritaco** [comment]
@mjneil important or cruft-n-close? :gun:

**Comment by LOZORD** [comment]
Nice terminology :laughing:

**Comment by mjneil** [comment]
If you guys want it, its as easy as adding in `<link href="https://afeld.github.io/emoji-css/emoji.css" rel="stylesheet">` to index.html

I think it is cruft, but its also minimal cruft that requires no more work than what I stated above, which makes it ok if it's desired.
