### ISSUE TITLE
Establish milestones and priorities for release

### ISSUE THREAD

**Issue by melutzke** [UW-UPL/uw-upl.github.io#40]
This might help emphasize which features are important for the new site to go live.

**Comment by LOZORD** [comment]
I think all info should be present (i.e. #35 and #37 ) at a minimum

@Squeakrats @bhans117

**Comment by katamaritaco** [comment]
Yeah I think that is it as well for release.

**Comment by Squeakrats** [comment]
I'll add my profile tomorrow

**Comment by katamaritaco** [comment]
:+1: :mouse2:

**Comment by LOZORD** [comment]
@mjneil are we ready to launch soon?
