### ISSUE TITLE
Update GitHub image with new logo

### ISSUE THREAD

**Issue by LOZORD** [UW-UPL/uw-upl.github.io#42]
@mjneil whichever one you think is most appropriate.

**Comment by mjneil** [comment]
its tooooo wide, what do? 
![image](https://cloud.githubusercontent.com/assets/2829052/12767026/5a9faa10-c9cc-11e5-8160-b9e2c4d09b27.png)

**Comment by LOZORD** [comment]
@MikeCook9994 do you want to Photoshop it?

**Comment by mjneil** [comment]
I can use photoshop, was just wondering how you want to alter it. The above screenshot is actually a scaled down version of the logo, but apparently when you scale it down, it just makes the "crop" region smaller too..

**Comment by katamaritaco** [comment]
Might not be right place for it, but we need those files for logo etc saved and accessible somewhere

Get Outlook for Android<http://aka.ms/ghei36>



On Tue, Feb 2, 2016 at 3:47 PM -0800, "Leo Rudberg" <notifications@github.com<mailto:notifications@github.com>> wrote:


@MikeCook9994<https://github.com/MikeCook9994> do you want to Photoshop it?

-

**Comment by mjneil** [comment]
@katamaritaco what do you mean? They are in the repo

**Comment by katamaritaco** [comment]
I mean for general use but didn't look since I'm on my phone

Get Outlook for Android<http://aka.ms/ghei36>



On Tue, Feb 2, 2016 at 3:51 PM -0800, "Matthew Neil" <notifications@github.com<mailto:notifications@github.com>> wrote:


@katamaritaco<https://github.com/katamaritaco> what do you mean? They are in the repo

-

**Comment by katamaritaco** [comment]
Done
:sweat_drops: :sweat_drops: :eggplant: :facepunch: :muscle:

**Comment by LOZORD** [comment]
Thank 😻🕴🎷🐸
