### ISSUE TITLE
Throw old website in general archive repo

### ISSUE THREAD

**Issue by katamaritaco** [UW-UPL/uw-upl.github.io#46]
I've brought up the need for a private 'archival' repo before. Would this be good to store? Only reaons I put this uissue in this repo is because if it should be done, it should happen after the redirect is set up.

**Comment by lwdinh** [comment]
I think it would be. There is value in preserving the old website for the future coords + for reference.

**Comment by LOZORD** [comment]
Probably just creating a zip file or tarball and saving it to a repo would be good.

**Comment by katamaritaco** [comment]
https://github.com/UW-UPL/Archives/issues/1
