### ISSUE TITLE
Add favicon

### ISSUE THREAD

**Issue by LOZORD** [UW-UPL/uw-upl.github.io#5]
We shouldn't have the default Yeoman favicon for our website.

**Comment by LOZORD** [comment]
https://umark.wisc.edu/brand/templates-and-downloads/web-logos.php

https://umark.wisc.edu/brand/templates-and-downloads/downloads/web/uwcrest_web_sm.png

How do people feel about these?

**Comment by katamaritaco** [comment]
LGTM

**Comment by LOZORD** [comment]
Actually, what do you think about using the new `wisc.edu` favicon?

http://www.google.com/s2/favicons?domain=www.wisc.edu
