### ISSUE TITLE
Link to slack

### ISSUE THREAD

**Issue by lwdinh** [UW-UPL/uw-upl.github.io#51]
Link to https://uw-upl.slack.com/

**Comment by lwdinh** [comment]
Besides creating a new account, what else would need to be done to allow users to join slack?

**Comment by LOZORD** [comment]
Maybe making sure they have a UPL account or are a UW student or are part of the Facebook group?

**Comment by katamaritaco** [comment]
:+1: to having a UPL account

**Comment by LOZORD** [comment]
Do we want software or wetware to check this condition?

**Comment by katamaritaco** [comment]
Honestly, I guess ti doesn't REALLY matter for the time being.Might be a nice enhancement though?

**Comment by LOZORD** [comment]
@katamaritaco @lwdinh Cruft or keep?

**Comment by katamaritaco** [comment]
I think slack is cruft in general, so I'm bias

**Comment by LOZORD** [comment]
The Slack channel seems kind of :skull: I think the majority of our communication should/will take place over email and Facebook. Do we want to #cruft this?

**Comment by katamaritaco** [comment]
I'm cool with that. I'd also be cool with ditching the slack channel in general (or moving to all private channels that are only active for events)

**Comment by LOZORD** [comment]
:-1: meaning :skull:
