### ISSUE TITLE
Lab Status is broken

### ISSUE THREAD

**Issue by lwdinh** [UW-UPL/uw-upl.github.io#52]
title

**Comment by Squeakrats** [comment]
It goes down every time the servers go down. I also can't restart it properly as I'm not sudo

**Comment by LOZORD** [comment]
Maybe give a link to the coords email?

**Comment by mjneil** [comment]
Can we close this?

**Comment by katamaritaco** [comment]
Leo wanted it to be so like, if all amchines are down, display messag telling to email coords or whatever. idk if that is what is going to happen or a different issue or what. idk. idk. idk.

:sweat_drops: :sweat_drops: :eggplant: :facepunch: :muscle:
:sweat_drops: :sweat_drops: :eggplant: :facepunch: :muscle::sweat_drops: :sweat_drops: :eggplant: :facepunch: :muscle::sweat_drops: :sweat_drops: :eggplant: :facepunch: :muscle::sweat_drops: :sweat_drops: :eggplant: :facepunch: :muscle::sweat_drops: :sweat_drops: :eggplant: :facepunch: :muscle::sweat_drops: :sweat_drops: :eggplant: :facepunch: :muscle::sweat_drops: :sweat_drops: :eggplant: :facepunch: :muscle::sweat_drops: :sweat_drops: :eggplant: :facepunch: :muscle::sweat_drops: :sweat_drops: :eggplant: :facepunch: :muscle::sweat_drops: :sweat_drops: :eggplant: :facepunch: :muscle::sweat_drops: :sweat_drops: :eggplant: :facepunch: :muscle::sweat_drops: :sweat_drops: :eggplant: :facepunch: :muscle::sweat_drops: :sweat_drops: :eggplant: :facepunch: :muscle::sweat_drops: :sweat_drops: :eggplant: :facepunch: :muscle::sweat_drops: :sweat_drops: :eggplant: :facepunch: :muscle::sweat_drops: :sweat_drops: :eggplant: :facepunch: :muscle:

**Comment by mjneil** [comment]
Done
