### ISSUE TITLE
Grey out/remove webcam slider if non-responsive

### ISSUE THREAD

**Issue by LOZORD** [UW-UPL/uw-upl.github.io#53]
I assume this is related to certain parts of the lab being down.

**Comment by lwdinh** [comment]
It's due to the script not being run by sudo user. Yusef says that ideally it would never be down.

**Comment by LOZORD** [comment]
So is this a bug? :scream:

**Comment by Squeakrats** [comment]
It's not really a bug. It's eris being shut off and me not being able to reboot it/wanting to bother John. I'll have John make a keepalive script (or I will if I'm admin)

**Comment by LOZORD** [comment]
@Squeakrats @jdetter any updates? :camel:

**Comment by Squeakrats** [comment]
I don't think there is a need for this as if the slider doesn't work neither does the Camera

**Comment by LOZORD** [comment]
Ok #crufted :-1: :skull:
