### ISSUE TITLE
Remove `console.log`s

### ISSUE THREAD

**Issue by LOZORD** [UW-UPL/uw-upl.github.io#55]
I've heard that this is a Good Practice :tm: for when we launch the site.

**Comment by katamaritaco** [comment]
Can we wrap them in some sort of #ifdebug? Not sure how W E B handles it

**Comment by LOZORD** [comment]
Yeah, we could basically monkeypatch it to an `noop` based on the current URL, i.e. _not_ `localhost`.

**Comment by katamaritaco** [comment]
Merged
:sweat_drops: :sweat_drops: :eggplant: :facepunch: :muscle:
