### ISSUE TITLE
Can we delete some unused logos?

### ISSUE THREAD

**Issue by katamaritaco** [UW-UPL/uw-upl.github.io#58]
I backed everything up here: https://github.com/UW-UPL/Media/

We should use that repo in the future for all upl related media

**Comment by mjneil** [comment]
go for it

**Comment by katamaritaco** [comment]
I'm just going to delete them all and fuck everything up

**Comment by mjneil** [comment]
I mean, dont delete the ones being used

**Comment by katamaritaco** [comment]
That is why I'm not doing it

**Comment by mjneil** [comment]
done

**Comment by katamaritaco** [comment]
tybb <3 u
