### ISSUE TITLE
Add support for mobile (?)

### ISSUE THREAD

**Issue by LOZORD** [UW-UPL/uw-upl.github.io#6]
Is this something we want to do?

There are several ways we could go about doing this, since the logic of the site doesn't need to change.

**Comment by mjneil** [comment]
So I have been writing the css to be a responsive layout so it works on mobile. You can even see this by resizing your browser, however I just noticed going to the site on my phone, it is not being responsive. Not sure why

**Comment by mjneil** [comment]
This should be fixed now

**Comment by LOZORD** [comment]
Looks pretty noice :+1:
