### ISSUE TITLE
Decouple Lab Status script from the lab itself

### ISSUE THREAD

**Issue by Ricky54326** [UW-UPL/uw-upl.github.io#60]
If the lab goes down, right now, the service status and webcam would go down too. Is there anything we can do about this?

**Comment by mjneil** [comment]
Well, can something be done? Sure a lot of things. What is it that you are looking for? Right now if the lab is down, we just put an error message on the Lab page and tell the user to email the coords list

**Comment by katamaritaco** [comment]
Yeah I'm confused to. Do you mean that you want the up/down on the lab to be hosted externally to the upl on a more 'reliable' server somewhere?

**Comment by Squeakrats** [comment]
Yea aside from spinning up an external server can't really do much

**Comment by Ricky54326** [comment]
Two options I can think of immediately:

1) Set up a Heroku dynamo/whatever it's called (I can help/set this up if need be) for the server status, but at that point we may as well use a library or something maybe?

2) Like @mjneil  said, possibly just say that the lab is down if we aren't able to get an accurate lab status.

**Comment by katamaritaco** [comment]
I think your 2) is already implemented @Ricky54326

**Comment by Ricky54326** [comment]
Let's just close this for now then. It's fine as-is. Someone can re-open if it becomes an issue.
