### ISSUE TITLE
Document the website and comment the code

### ISSUE THREAD

**Issue by MikeCook9994** [UW-UPL/uw-upl.github.io#62]
Because we should.

**Comment by Ricky54326** [comment]
At the very least, a tl;dr guide with:

1) What to do to add a new page/view, not everyone knows how to do this, esp with angular
2) Where are all the config files, particularly for lab status ( see #61 )

**Comment by LOZORD** [comment]
I think having an md file about the pattern that Matt's been using (factories with `.populate`) would be very helpful for people in the future.

**Comment by LOZORD** [comment]
@MikeCook9994 adding tests is a great way to document :+1: :grinning: :+1:

**Comment by LOZORD** [comment]
No longer relevant with upcoming move to Jekyll.
