### ISSUE TITLE
Contact CSL to see if they can add a CNAME or A record to point to github servers

### ISSUE THREAD

**Issue by katamaritaco** [UW-UPL/uw-upl.github.io#63]
From @mjneil :
ricky said we have to contact csl
to see if they can add a CNAME or A record
to point to github servers

**Comment by Ricky54326** [comment]
just reached out to CSL about this, hope we hear back soon.


________________________________

**Comment by Ricky54326** [comment]
from CSL:


"The primary name server (master) for upl.cs.wisc.edu (the entire zone) is a UPL computer: 128.105.45.102

We get the zone data from your server, and are a secondary authoritative nameserver for the zone.

If you make the change in your nameserver, it will propogate to the internet.

 --david"

So, I guess we can indeed make the changes in our own DNS server. I'll do this within the next couple of days and close the issue.


________________________________

**Comment by katamaritaco** [comment]
Thanks.


wen davi partur iz lik "bt u guise handl it ya dingalus"


________________________________

**Comment by LOZORD** [comment]
:camel:

**Comment by LOZORD** [comment]
@Ricky54326 any update? Can we close?

**Comment by Ricky54326** [comment]
Yeah this is taken care of now. Our DNS propagates its changes to CSL automatically, so we just have to make changes ourselves and they get them every so often.
