### ISSUE TITLE
Add Randy's photo

### ISSUE THREAD

**Issue by LOZORD** [UW-UPL/uw-upl.github.io#64]
Remember that it needs to be square and relatively small (for load speed).

**Comment by LOZORD** [comment]
:point_right: bump

**Comment by katamaritaco** [comment]
randy plz

**Comment by ranman166** [comment]
I'll be able to add it this weekend I was going to take another pic for it.

**Comment by ranman166** [comment]
My friend couldn't take the photo this weekend, so i'll just put up a placer holder (still a photo of me) tomorrow.

**Comment by melutzke** [comment]
bampersand
