### ISSUE TITLE
'Wave' button on webcam

### ISSUE THREAD

**Issue by katamaritaco** [UW-UPL/uw-upl.github.io#65]
Might be ncie to have a 'wave' button that automatically 'waves' the webcam at people. put a 5 second timeout on it or soemthing.

**Comment by Squeakrats** [comment]
Yes this doable

**Comment by LOZORD** [comment]
Maybe have some LED blink or have some sort of chime sound?

**Comment by LOZORD** [comment]
@ekivolowitz I'm assigning you because (1) you're around this summer (2) you've worked with hardware before (3) you are related to the person who would abuse this the most.

**Comment by ekivolowitz** [comment]
Neat. I'll still have questions out the wazoo because I've never dealt with something like this.

**Comment by jdetter** [comment]
I think we decided this is cruft, but I think Randy and Yusef are still working on the servo problem.
