### ISSUE TITLE
Figure out way to hook up webcam to get position

### ISSUE THREAD

**Issue by katamaritaco** [UW-UPL/uw-upl.github.io#66]
This way, the slider won't always start in middle. It should start where webcam is already tilted at.

**Comment by Squeakrats** [comment]
I've never touched arudinoy stuff but from webserver side this is easy

**Comment by LOZORD** [comment]
@ekivolowitz or @Squeakrats, would either of you be up for taking care of this?

**Comment by Ricky54326** [comment]
I think we already did this? Please re-open if not. Closing.
