### ISSUE TITLE
add image for upl games event

### ISSUE THREAD

**Issue by katamaritaco** [UW-UPL/uw-upl.github.io#68]

**Comment by LOZORD** [comment]
See https://github.com/UW-UPL/Talks/issues/9

**Comment by katamaritaco** [comment]
Waiting on stuff in Talks#9

**Comment by LOZORD** [comment]
Ah nice

B L O C K E D
L
O
C
K
E
D

**Comment by LOZORD** [comment]
So I have the images now (poster and FB banner). However, the image code is [commented out](https://github.com/UW-UPL/uw-upl.github.io/blob/master/views/events.html#L8). @mjneil do you mind if I bring it back in?

**Comment by LOZORD** [comment]
:camel:

**Comment by mjneil** [comment]
Sure go for it. If you guys have some changes for the site that are ready to go and work and what not, feel free to merge it in.

**Comment by LOZORD** [comment]
Are people ok with closing this?

**Comment by katamaritaco** [comment]
Yeah, event already happened.
