### ISSUE TITLE
Reason for linking events to gh page?

### ISSUE THREAD

**Issue by katamaritaco** [UW-UPL/uw-upl.github.io#69]
Is there a reason the main event headers in the events page link to a special event page? Maybe we could instead use those headers to point to facebook events or whatnot?

**Comment by LOZORD** [comment]
FYI, we have the ability to embed `<a>` links in the content section of the events. I'm fine either way though. One possible snafu is that if there _isn't_ an FB event, but we'd still like to list it on our site.

**Comment by katamaritaco** [comment]
Knowing about adding an href is nice. The thing I just think is cruft now is that when a user clicks the main event title header, it brings to a random single page that doesn't seem to be useful, you know what I mean?

**Comment by LOZORD** [comment]
Do you think adding an __optional__ `facebook` or `external_url` field to the `events` JSON might be useful?

**Comment by katamaritaco** [comment]
Yeah.

Do you think the event header linking to random page is keep or cruft tho?

**Comment by LOZORD** [comment]
I think it is good. For example if we want to link people to a specific
event.

**Comment by katamaritaco** [comment]
Ok. Other opinions. @mneil ?

Get Outlook for Android<http://aka.ms/ghei36>



On Wed, Feb 24, 2016 at 6:51 AM -0800, "Leo Rudberg" <notifications@github.com<mailto:notifications@github.com>> wrote:

I think it is good. For example if we want to link people to a specific
event.

On Wednesday, February 24, 2016, Nick Heindl <notifications@github.com>
wrote:

> Yeah.
>
> Do you think the event header linking to random page is keep or cruft tho?
>
> -
> Reply to this email directly or view it on GitHub
> <https://github.com/UW-UPL/uw-upl.github.io/issues/69#issuecomment-188110024>
> .
>

-

**Comment by LOZORD** [comment]
:camel:

**Comment by katamaritaco** [comment]
whatever -> just close it (Y)
