### ISSUE TITLE
Webcam mobile support

### ISSUE THREAD

**Issue by Squeakrats** [UW-UPL/uw-upl.github.io#71]
there is a way to stream video via web sockets (that apparently is actually pretty good) 
This would allow us to stream to any browser that supports a canvas (specifically mobile)

**Comment by LOZORD** [comment]
See: https://developer.mozilla.org/en-US/docs/Web/HTML/Supported_media_formats

As with #79, we may need to change the video format to something more pedestrian like `mp4` or `aac`.

**Comment by Ricky54326** [comment]
Closing for now - we tried to do this, but iOS still doesn't and probably won't ever work unfortunately.
