### ISSUE TITLE
Add support for project Images and links with those images.

### ISSUE THREAD

**Issue by spwilson2** [UW-UPL/uw-upl.github.io#74]
I tried adding an image to the projects page and it's not displaying. Are images not set up to display here?

**Comment by mjneil** [comment]
No they are not supported yet. Never got around to adding them into the layout, definitely should be added though

**Comment by LOZORD** [comment]
Would it just be a photo in the `content/projects` directory like `content/coords`? Or would we try to pull it from some sort of external source?

**Comment by spwilson2** [comment]
Also could we possibly add a clickable link attached to the image? Forr
instance, I'd like the riscv picture to go to their landing page.

**Comment by LOZORD** [comment]
Making the description text parsed as HTML might also be an option. I did something similar for events.
