### ISSUE TITLE
Sort (first N) projects by latest commit

### ISSUE THREAD

**Issue by LOZORD** [UW-UPL/uw-upl.github.io#75]
We could use the GitHub API to sort projects by latest commit. A flaw might be if projects aren't hosted on GitHub. I'm fine closing this issue if people think it's cruft.

**Comment by mjneil** [comment]
I think this would be cool for which projects are featured on the home page, but probably would just be nice for alphabetical order or something on the actual projects page?

**Comment by LOZORD** [comment]
I'm on it Soon™

**Comment by LOZORD** [comment]
Helpful links:

https://developer.github.com/v3/git/refs/
http://stackoverflow.com/questions/15919635/on-github-api-what-is-the-best-way-to-get-the-last-commit-message-associated-w

**Comment by LOZORD** [comment]
@zthomae do you want me to take care of this? Or do you have it?

**Comment by zthomae** [comment]
Sure, you can handle it again. Make sure to file another pull request so @MikeCook9994 and I can review it.
