### ISSUE TITLE
Lab status page broken if used with https

### ISSUE THREAD

**Issue by LOZORD** [UW-UPL/uw-upl.github.io#76]
https://uw-upl.github.io/#/lab

Here's the error message:

```
Mixed Content: The page at 'https://uw-upl.github.io/#/lab' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://eris.upl.cs.wisc.edu:1312/lab-status'. This request has been blocked; the content must be served over HTTPS.
```

So basically, do we want to add `https` to eris?

**Comment by Squeakrats** [comment]
Uh the URL in code can prob just have an s added to it.

**Comment by LOZORD** [comment]
@Squeakrats do you mind taking care of it?

**Comment by Squeakrats** [comment]
I'll try

**Comment by LOZORD** [comment]
:camel:

**Comment by spwilson2** [comment]
:camel:

**Comment by Squeakrats** [comment]
Oh yea I forgot about this. I believe the issue was that I needed to create an Https Cert? I probably should know this but does anyone know if thats how that works? Im pretty sure the issue was https pages cant do anything over http (which the webcam was) and to make the webcam https you need https certs.

**Comment by Squeakrats** [comment]
* I also think adding it is more of a hassle than its worth. Adding https doesn't really get us anything.

**Comment by Squeakrats** [comment]
Leo would you have a problem with just re-directing https to http?

**Comment by spwilson2** [comment]
Is there any way we could redirect to an https page that warns about going to unencrypted http beforehand? I reaally don't like the idea of redirecting from https to http

**Comment by Squeakrats** [comment]
Probably.  But like what content do we have that would need to be over https?

**Comment by spwilson2** [comment]
It's mostly about the principle to me, if you really want we can discuss at coord meeting tho

**Comment by Squeakrats** [comment]
suar

**Comment by LOZORD** [comment]
Redirecting is a non-optimal solution. Up to you guys.

**Comment by LOZORD** [comment]
FYI: https://github.com/blog/2186-https-for-github-pages

**Comment by spwilson2** [comment]
As far as I know the problem isn't on the github side, but on the eris
side. Github HTTPS is working fine it's the trying to get lab status from
eris over HTTPS that's the issue. (I think)

**Comment by Squeakrats** [comment]
Yup I believe so too.

**Comment by Ricky54326** [comment]
Merging with #110 .
