### ISSUE TITLE
Webcam doesn't work on safari

### ISSUE THREAD

**Issue by mjneil** [UW-UPL/uw-upl.github.io#79]
If someone that uses a mac could debug and fix this, that's be super cool

**Comment by LOZORD** [comment]
This might help diagnose: http://caniuse.com/#info_about

**Comment by LOZORD** [comment]
Be sure to put in "dead text" like if an `<img>` doesn't show up.

https://developer.apple.com/library/safari/documentation/AudioVideo/Conceptual/Using_HTML5_Audio_Video/AudioandVideoTagBasics/AudioandVideoTagBasics.html

**Comment by melutzke** [comment]
Second m'neils request, I tried super hard to get iOS and osx to be useful devices, but I failed. If it helps, look in to something called HLS for apple compat.

**Comment by LOZORD** [comment]
Well here you go: Safari (and several others) [do not support the `webm` format](http://caniuse.com/#feat=webm). Unless we change the source (or provide an alternate) or do something crazy on the front-end, I think we're stuck.

**Comment by jdetter** [comment]
I think this was probably fixed by our latest webcam edits. I don't see why it wouldn't work on Safari with our new design.

**Comment by LOZORD** [comment]
Doesn't work for my Safari

```
[Warning] The page at https://uw-upl.github.io/ was allowed to display insecure content from http://siren.upl.cs.wisc.edu:1312/webcam-frame.jpg?0.7545398265397039. (uw-upl.github.io, line 1)
```

**Comment by Squeakrats** [comment]
Yea that is part of another issue for getting certs for the cam computer

**Comment by jdetter** [comment]
Does it actually not work on Safari or does it just print that message out?

**Comment by Squeakrats** [comment]
Tested on jazz's phone it does not. I assume they  block it completely . (Where chrome just gives you a warning)

**Comment by LOZORD** [comment]
Yeah nothing even showed up. @Squeakrats , I'm pretty sure it's an iOS problem and not a browser problem in the context of phones. But yeah, Safari didn't work on my laptop.

**Comment by Ricky54326** [comment]
Closing for now, re-open if we intend to fix at some point.
