### ISSUE TITLE
Switch to Jekyll

### ISSUE THREAD

**Issue by LOZORD** [UW-UPL/uw-upl.github.io#88]
This issue will track @zthomae's work on the `jekyll` branch. Please discuss below:

**Comment by LOZORD** [comment]
I am in favor of the switch because of __reduced overhead__ (the templating language is easier for learning and maintenance than Angular).

**Comment by zthomae** [comment]
Moving to Jekyll has already been agreed upon (see the slack #website channel logs). This issue is a suitable place for code review, but we will not relitigate the decision to move to jekyll here.

**Comment by LOZORD** [comment]
Ah sorry! I though the Slack was toten 😀

**Comment by zthomae** [comment]
Done with the merge of #89
