### ISSUE TITLE
Add UW-UPL GitHub metadata

### ISSUE THREAD

**Issue by LOZORD** [UW-UPL/uw-upl.github.io#91]
This is not necessarily related to my work in #75, but [this gem](https://github.com/jekyll/github-metadata) is worth looking at.

**Comment by zthomae** [comment]
We already have this.

**Comment by LOZORD** [comment]
Do you get a message about it when running Jekyll though?

**Comment by LOZORD** [comment]
```
GitHub Metadata: No GitHub API authentication could be found. Some fields may be missing or have incorrect data.
```

**Comment by zthomae** [comment]
You only need to authenticate for certain features of the plugin. Since we don't use the gem at all right now, I'm not concerned about this.
