### ISSUE TITLE
Kebab and escape all intra-site URLs

### ISSUE THREAD

**Issue by LOZORD** [UW-UPL/uw-upl.github.io#92]
See about slugify and others here: https://jekyllrb.com/docs/templates/

This could lead to potential problems (e.g. projects with spaces in the name).

Also not the behavior we want when emailing URLs, for example.

**Comment by LOZORD** [comment]
Also, we should just grep all anchor tags. The `join us` link on the front page still uses the link style from the Angular version, for example.

**Comment by MikeCook9994** [comment]
Did @zthomae do this in one of his PRs?

**Comment by zthomae** [comment]
The anchor tag is fixed, and the project links are escaped. I'm closing this because I don't think there's an issue left to fix.
