### ISSUE TITLE
Move upl-services to a different repo

### ISSUE THREAD

**Issue by zthomae** [UW-UPL/uw-upl.github.io#94]
The website services are not a part of the site's source code and belong somewhere else.

**Comment by jdetter** [comment]
which services?

**Comment by LOZORD** [comment]
These ones: https://github.com/UW-UPL/uw-upl.github.io/tree/develop/upl-services

There may be others too. We might want to wait until `develop` is merged back into `master` though (?).

**Comment by jdetter** [comment]
Which repo should this go in? UPL-Config?

**Comment by LOZORD** [comment]
Yeah, I think so, since that is the code that will get deployed to the servers. See https://github.com/UW-UPL/UPL-Config/issues/58

**Comment by MikeCook9994** [comment]
this is done on both repos. Closing. If we have a script that we use to deploy our services that will break and will have to be fixed.
